version: '3.8'

services:
  gateway:
    build: ./gateway
    ports: 
      - "3000:80"
    networks:
      - connect
    environment:
      - SERVER_ADDRESS=0.0.0.0:80
      - AUTH_SERVICE_ADDRESS=authentication:80
      - GIN_MODE=release
    depends_on:
      - authentication

  authentication:
    build: ./authentication
    networks:
      - connect
    environment:
      - PORT=80
    depends_on:
      - authentication-db

  authentication-db:
    image: postgres:alpine3.17
    ports:
      - "3001:5432"
    networks:
      - connect
    environment:
      - POSTGRES_USER=surajboniwal
      - POSTGRES_PASSWORD=suraj1335
      - POSTGRES_DB=socialmedia
    volumes:
      - ./volumes/authentication-db:/var/lib/postgresql/data

networks:
  connect:
    name: "connect"